project:
  type: website
  output-dir: docs
  resources:
    - "assets/"

filters:
  - remove-polyfill.lua

website:
  title: "Jiahao Tian"
  site-url: "https://jhao1122.github.io"
  google-analytics: "G-MPD6ZGWYW1"

  navbar:
    title: false
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: Projects/index.qmd
        text: Research
      - href: Talks/index.qmd
        text: Talks
      - href: Teaching/index.qmd
        text: Teaching
      - href: https://jhao1122.github.io/Notes/
        text: Notes
      - href: assets/Curriculum_Vitae.pdf
        text: CV

  page-footer:
    border: false
    left: "© 2026 Jiahao Tian"
    right: "Força Barça! 🔵🔴"

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    dark-mode-switch: true
    toc: true
    toc-depth: 2
    smooth-scroll: true
    number-sections: false
    link-external-newwindow: true
    html-math-method:
      method: mathjax
      url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml-full.js"