project:
  type: website
  output-dir: docs
  resources:
    - "assets/"

website:
  title: "Jiahao's Space"
  google-analytics: "G-MPD6ZGWYW1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects/index.qmd
        text: Projects
      - href: Teaching/index.qmd
        text: Teaching
      - href: https://jhao1122.github.io/Notes/
        text: "Academic Notes"
  page-footer:
    left: "© 2026 Jiahao Tian"
    right: "Força Barça! 🔵🔴"

format:
  html:
    theme: 
      - cosmo         
      - custom.scss   
    toc: true         
    number-sections: false

